### ISSUE TITLE
"unique" weapons

### ISSUE THREAD

**Issue by nut4050** [Ovikx/exalt-public#28]
they would be like rarer than s tier and idk instead of having just a raw stat boost they could have like some coolio ability tacked onto them or something idk

**Comment by nut4050** [comment]
already know this is gonna get cancelled but i want it so i post anyways

**Comment by Ovikx** [comment]
yeah idk about this because designing a unique weapon class will require revamping how weapons are stored in the database. the database format was designed with a scope that this idea unfortunately doesn't fall into. i high key don't think the benefits outweigh the costs in terms of development time.

**Comment by nut4050** [comment]
sounds like cope

**Comment by Ovikx** [comment]
i'm speaking facts
