### ISSUE TITLE
sort by stats

### ISSUE THREAD

**Issue by nut4050** [Ovikx/exalt-public#44]
eg. sorting by weapon damage / slots

also maybe you could do this for stat mods too bc that would be hot but that would probably be dumb considering the stats dont display on the inventory paeg

**Comment by Ovikx** [comment]
this would be really inefficient to implement; what I can do however, is sort weapons and armor by their damage/defense stats after they are sorted by their class. it wouldn't be perfect (because of stat overlap among classes), but it's the best I can think of right now. basically, sorting by class also sorts by damage/defense in each class.

**Comment by Ovikx** [comment]
example:
input: /inventory sort:Class
output: 
![image](https://user-images.githubusercontent.com/47368700/222991395-049d55e8-1dcc-4842-a8ee-74692f7a290d.png)
