### ISSUE TITLE
Weapon slots being useless in late game

### ISSUE THREAD

**Issue by Unlamped** [Ovikx/exalt-public#75]
When upgrading 15 slot s tier weapons, I am unable to put all the itmes I want on it despite having 20 slots which is more than enough, since im capped at 4 stat mods as well as being capped at moves, the extra slots I have are pointless, I believe that moves should not have a cap on them, or exalted mods should have a low chance for a 3rd stat but make the mod cost extra slots. The third stat could be a duplicate previous stat or something else like debuff buff or something, or like dodge chance, idk.

**Comment by Ovikx** [comment]
You aren't considering move upgrades. I'm assuming you're talking about shield in particular since it doesn't have many upgrades yet. I'm not going to accomodate the lack of upgrades by removing caps and potentially ruining balancing. I also have no idea what you're talking about in the latter half of your issue. I'm closing this because it seems to be two loosely relevant suggestions in one post; create another issue if you care to expand.
